### PR TITLE
Fix deprecation for symfony/config 4.2+

### PR DESCRIPTION
**Pull request by bits4breakfast**
Heavily inspired by https://github.com/symfony/maker-bundle/pull/324

### CODE REVIEW

**Comment by bits4breakfast** [comment]
hi @howardlopez - what's the process for submitting a new PR? Thanks!

**Comment by howardlopez** [comment]
@bits4breakfast - You can update this PR by simply committing to the branch to be merged. It will trigger a new round of Travis tests.

**Comment by bits4breakfast** [comment]
@howardlopez - thanks. But are tests going to fail again for those PHP 5.3? Are they still supported?

**Comment by howardlopez** [comment]
The Travis builds are currently failing for the PHP 5.5 and 5.6 builds, which are still supported. Since it's a memory limit issue, we'll have to look into the configuration to make sure it's set up in such a way that it can actually pass.

**Comment by howardlopez** [comment]
Closing and re-opening PR to trigger fresh Travis CI build with new Travis file.

**Comment by alegout** [comment]
thank you @howardlopez

**Pull request merged**
