### PR TITLE
Update aws-sdk-php to latest version

### PR DESCRIPTION
**Pull request by egorzot**
- Updates php version to 8.0
- Updates symfony version
- Fix tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SamRemis** [comment]
Once the deprecation is official, then we will be able to move forward with this and I'll give it a more in-depth review

**Comment by alexbaileyuk** [comment]
@SamRemis we are unable to use this wrapper for the Event Bridge functionality we need since the included SDK version does not have the `\Aws\EventBridge` namespace. Is this likely to be updated any time soon or should we consider removing the wrapper and just installing the SDK itself?

**Comment by SamRemis** [comment]
@alexbaileyuk 
Thanks for drawing this to my attention again.  While the deprecation is moving along, it hasn't been officially announced yet; it looks like it will be soon.  I'm inches away from having it officially approved, and I'm hoping to get it fast-tracked as much as I can.  In the meantime, I'd happily accept a PR that uses `#[\ReturnTypeWillChange]`  in place of the return types and any other non PHP 5.5 compatible code I may have missed.

**Comment by alexbaileyuk** [comment]
@SamRemis thanks for a speedy response. Unfortunately we are under some tight time constraints and are unable to contribute or wait for the update.

For now, we only use two or three services from the SDK so we have decided to install the SDK directly and create the service definitions for those few service clients ourselves sucha as:

```
services:
    membr.aws.s3_client:
        class: Aws\S3\S3Client
        factory: [ Aws\S3\S3Client, 'factory' ]
        arguments:
            - version: latest
              region: eu-west-1

    membr.aws.sqs_client:
        class: Aws\Sqs\SqsClient
        factory: [ Aws\Sqs\SqsClient, 'factory' ]
        arguments:
            - version: latest
              region: eu-west-1
```

**Comment by yenfryherrerafeliz** [comment]
Hi @egorzot, thanks for working on this. We have introduced the changes suggested on this PR in the following [release](https://github.com/aws/aws-sdk-php-symfony/releases/tag/2.7.0). Please feel free to reach out for anything we may help with.

Thanks!

**Pull request closed without merging**
