### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by ttomdewit**
*Issue #, if available:*
Solves #102

*Description of changes:*
Add 7 range to Composer file for Symfony related packages.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This would be amazing :pray: , it's the last blocker for Symfony 7 upgrade

**Comment by ttomdewit** [comment]
I am working on getting the tests to succeed since just the Composer changes won't cut it 😢.

**Comment by ttomdewit** [comment]
I also noticed https://github.com/aws/aws-sdk-php-symfony/pull/81 where the modernisation of the tool is mentioned for PHP 8 support, I wonder if the same will happen here (I imagine so).

**Comment by TomasVotruba** [comment]
@ttomdewit Wow, 2 years old PR. Seems like this package is abandoned for good. I'll see how much work would fork take

**Comment by TomasVotruba** [comment]
Seems one of these last week active forks could be a good candidate:
https://github.com/aws/aws-sdk-php-symfony/forks?include=active&page=1&period=1mo&sort_by=stargazer_counts

**Comment by TomasVotruba** [comment]
Fork/work in progress: https://github.com/TomasVotruba/aws-sdk-php-symfony/pull/1

**Comment by ttomdewit** [comment]
> Fork/work in progress: [TomasVotruba/aws-sdk-php-symfony#1](https://github.com/TomasVotruba/aws-sdk-php-symfony/pull/1)

@TomasVotruba you work fast 😛

**Comment by ttomdewit** [comment]
> @ttomdewit Wow, 2 years old PR. Seems like this package is abandoned for good. I'll see how much work would fork take, as we want to go Symfony 7 this/next week

Yeah sadly, I am already considering alternatives (just use the PHP SDK without the Symfony bundle stuff or alternatively I've been told about https://async-aws.com/)

**Comment by TomasVotruba** [comment]
I have to, so it's working today :) 

Here is tagged package to try out 
https://packagist.org/packages/tomasvotruba/aws-sdk-php-symfony

**Comment by ttomdewit** [comment]
> I have to be fast, so it's working today :)
> 
> Here is tagged package to try out https://packagist.org/packages/tomasvotruba/aws-sdk-php-symfony
> 
> Feedback is appreciated 👍

Let me give it a try tomorrow. Will report back.

**Comment by victormacko** [comment]
Nice one @TomasVotruba ! Any chance you're able to submit a PR so your changes can be part of the official repo? .. that way everyone can stay updated as other changes are contributed. Thank you for all your work & happy new year!

**Comment by TomasVotruba** [comment]
@victormacko Thanks, once this PR and the PHP 8.0 gets merged, I'd be happy to send PR.
But I think this repo is abandoned past 2 years.

**Comment by ttomdewit** [comment]
> I have to be fast, so it's working today :)
> 
> Here is tagged package to try out https://packagist.org/packages/tomasvotruba/aws-sdk-php-symfony
> 
> Feedback is appreciated 👍

Looking good! There is a release happening soon at `devizzent/cebe-php-openapi` so I used a dev tag for that one, but everything else is installing nicely and my QA tooling tells me we're solid 👍.

**Comment by TomasVotruba** [comment]
@mehmetsen80 Awesome! It's up and running past 3 weeks :+1: 

https://github.com/aws/aws-sdk-php-symfony/pull/103#issuecomment-1878973379

**Comment by mehmetsen80** [comment]
@TomasVotruba Unfortunately, the composer require aws/aws-sdk-php-symfony  has still conflicts for Symfony 7

 aws/aws-sdk-php-symfony[2.1.0, ..., 2.2.2] require symfony/config ~2.3|~3.0|~4.0|~5.0 -> found symfony/config[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.31] but these were not loaded, likely because it conflicts with another require.

**Comment by yenfryherrerafeliz** [comment]
Hi @ttomdewit, thanks for your contribution. We did create a new PR, based on this one, for addressing this and we also introduced other changes such as deprecating PHP versions below 7.2.5 and adding support for PHP 8 and up. Those new changes are now available in the following [release](https://github.com/aws/aws-sdk-php-symfony/releases/tag/2.7.0).

So please folks reach out if you need anything else that we can help with.

Thanks!

**Pull request closed without merging**
